### ISSUE TITLE
希望能增加 element 表单组件的 size 属性设置

### ISSUE THREAD

**Issue by xing240** [ncform/ncform#105]
希望能增加 element 表单组件的 size 属性的设置，用于控制表单组件的尺寸

[element form 表单组件文档](https://element.eleme.cn/#/zh-CN/component/form)，size 属性内容如下

参数 | 说明 | 类型 | 可选值 | 默认值
-- | -- | -- | -- | --
size | 用于控制该表单域下组件的尺寸 | string | medium / small / mini | -

@daniel-dx

**Comment by F-loat** [comment]
基础组件的 props 是否直接通过 v-bind 来透传更好一些
