### ISSUE TITLE
能否增加 同层级字段分组的功能  类似html5 中基础功能 <filedset >标签   非常重要！！！

### ISSUE THREAD

**Issue by zhugunzi** [ncform/ncform#114]
类似 以下字段配置 则将 name 和age 添加到 person 分组下
{
  "type": "object",
  "properties": {
    "age": {
      "type": "string",
      "ui": {
        "label": "age"，
        "filedset ":"person"
      }
    }   "name": {
      "type": "string",
      "ui": {
        "label": "name"，
        "filedset ":"person"
      }
    }
  }
}
![image](https://user-images.githubusercontent.com/30099116/67841532-46214480-fb33-11e9-98dd-59a1b8847998.png)

**Comment by daniel-dx** [comment]
你可以考虑这种效果代替：

![image](https://user-images.githubusercontent.com/22042268/67844809-5f2cf400-fb39-11e9-8714-85d20228c3be.png)

在 [Playground](https://ncform.github.io/ncform/ncform-show/playground/index.html) 选择 `Basic-Separator`

**Comment by zhugunzi** [comment]
> 你可以考虑这种效果代替：
> 
> ![image](https://user-images.githubusercontent.com/22042268/67844809-5f2cf400-fb39-11e9-8714-85d20228c3be.png)
> 
> 在 [Playground](https://ncform.github.io/ncform/ncform-show/playground/index.html) 选择 `Basic-Separator` 看下配置和效果

要是能折叠就好了

**Comment by daniel-dx** [comment]
如果要折叠就要使用 `object` 或 `array` 类型的 widget 了

**Comment by F-loat** [comment]
使用 `object ` 组件会使数据增加一层嵌套，可以用下面的 `flattenObject` 方法自动将 `$` 开头的字段内的属性提取至外层，并将 `_` 开头的字段移除，之后通过 `groupObject` 方法可将保存的转换后数据还原

``` ts
const groupObject = (data, schema) => {
  if (ncformUtils.isNormalArrSchema(schema)) {
    return data.map((curVal) => groupObject(curVal, schema.items))
  }

  if (!ncformUtils.isNormalObjSchema(schema)) {
    return data
  }

  return Object.keys(schema.properties).reduce((result, curKey) => {
    const curProp = schema.properties[curKey]

    if (/^\$/.test(curKey) && ncformUtils.isNormalObjSchema(curProp)) {
      return {
        ...result,
        [curKey]: groupObject(data, curProp)
      }
    }

    return {
      ...result,
      [curKey]: groupObject(data[curKey], curProp)
    }
  }, {})
}

const flattenObject = (data) => {
  if (typeof data !== 'object' || data === null) {
    return data
  }

  if (Array.isArray(data)) {
    return data.map(flattenObject)
  }

  return Object.keys(data).reduce((result, curKey) => {
    const curVal = flattenObject(data[curKey])

    if (/^_/.test(curKey)) {
      return result
    }

    if (/^\$/.test(curKey) && typeof curVal === 'object') {
      return {
        ...result,
        ...curVal
      }
    }

    return {
      ...result,
      [curKey]: curVal
    }
  }, {})
}
```
