### ISSUE TITLE
dx expression for selecting the main object in a array-tab

### ISSUE THREAD

**Issue by dhertzb** [ncform/ncform#126]
Now my form return this:

"client_location": [
    {
      "postalcode": "",
      "country": 174982,
      "state": 409313,
      "city": 616916,
      "adress": ""
    },
    {
      "postalcode": "",
      "country": 24324,
      "state": 2344,
      "city": "1039120",
      "adress": ""
    },
  ]

In this form the user will be able to create various locations, but just one to be the main. My solution to this is create a  select box where the user choose which object is the main location, so if one in the array tab is set to true all the others need automatically to be false, using dx expression how can I implement this?

The ideal response would be something like this:

"client_location": [
   main: {
      "postalcode": "",
      "country": 174982,
      "state": 409313,
      "city": 616916,
      "adress": ""
    },
    {
      "postalcode": "",
      "country": 24324,
      "state": 2344,
      "city": "1039120",
      "adress": ""
    },
  ]

**Comment by daniel-dx** [comment]
I suggest you put these logics into a custom widget

**Comment by daniel-dx** [comment]
Add `selected` field to location item, if selected, the item is the main item.

Refer to the [demo](https://codepen.io/daniel-dx/pen/XWbJeLz)

**Comment by dhertzb** [comment]
Thank you!

**Comment by dhertzb** [comment]
Sorry for bring it back but my form is passing by an api and I can't send functions in json, Can I achieve the same result just with dx expressions?

**Comment by dhertzb** [comment]
@daniel-dx

**Comment by dhertzb** [comment]
I need to reproduce the same comportament here https://codepen.io/daniel-dx/pen/XWbJeLz but just with dx expression because I can't send json with 'function()' through http responses @daniel-dx
