### ISSUE TITLE
range slider?

### ISSUE THREAD

**Issue by soundreactor** [ncform/ncform#127]
hi

does it work for the input type range?

**Comment by daniel-dx** [comment]
Of course. 

You can get the slider by two ways. An example is shown below:

```
{
  "type": "object",
  "properties": {
    "age1": {
      "type": "number",
      "ui": {
        "widgetConfig": {
          "type": "range"
        }
      }
    },
    "age2": {
      "type": "number",
      "ui": {
        "widget": "slider"
      }
    }
  }
}
```

> Note: use  `type:range` widget config of input widget, you need to add a class for it to display properly

```
.el-input__inner[type=range] {
    -webkit-appearance: slider-horizontal;
}
```
**I strongly recommend you to use the `slider` widget**
