### ISSUE TITLE
i18n 如何切換和擴充?

### ISSUE THREAD

**Issue by cgh20xx** [ncform/ncform#130]
1. 請問如何切換 ncform 內建的 i18n 語系?
2. 請問如何擴充 ncform 內建組件的其它語系呢？
謝謝

**Comment by daniel-dx** [comment]
1. 請問如何切換 ncform 內建的 i18n 語系? 

請參考：[ncform](https://github.com/daniel-dx/ncform-demo/blob/master/src/main.js)
```
Vue.use(vueNcform, {
  extComponents: Object.assign(ncformStdComps, { MyCustomComp }),
  extRules: [{ myCustom: MyCustomRule }],
  lang: "" // you can try 'en' or 'zh-cn'
});
```

2. 請問如何擴充 ncform 內建組件的其它語系呢？

當前如果要擴充內建組件的其它語系，只能把 `ncform-theme-elementui` 項目 fork 出來，然後進行代碼上的修改。
 
因為之前考慮到每個用戶的i18n實現方案不盡相同，所以內建組件的i18n數據都是寫在組件代碼裏面，並沒有抽離出來，後面會看反饋考慮是否需要抽離出來

**Comment by cgh20xx** [comment]
> 1. 請問如何切換 ncform 內建的 i18n 語系?
您好 目前是在 Vue.use 時就要指定語系，有辦法在不刷新頁面就直接切換嗎？
類似 vue-i18n 可使用 this.$i18n.locale = 'en' 即時切換
謝謝

**Comment by daniel-dx** [comment]
暫時沒有提供切換語言的方法，只能在 use 的時候用。

不過妳暫時可以采取以下取巧的方法來實現：
1. 切換語言時將 window.__$ncform.lang = ‘your lang’
2. 通過 v-if 讓 ncform 重新渲染即可
