### ISSUE TITLE
Request for custom widget

### ISSUE THREAD

**Issue by dhertzb** [ncform/ncform#132]
Method for emit error through custom widget to the form, something like the  _processModelVal() does with the value.

This is useful for widgets that have more than one input and some advanced logics.

Example: 

CUSTOM WIDGET
------------------------------
.     1  ------------------      .
.                                         .
.     2 ------------------       .
.                                         .
.     3 ------------------       .
.                                         .
------------------------------
1) Input with one validation
2) Input with other validation
3) Input with and other validation

- When form submit event is triggered it only verify the validation for the custom component wrapper

My custom widget now have about 7 inputs an it would be a lot more clean if I could handle it inside the custom widget and only triggers to the form.

**Comment by daniel-dx** [comment]
I think you can add a custom validation rule for your custom widget

**Comment by dhertzb** [comment]
Sorry for bring it back but my form is passing by an api and I can't send functions in json, Can I achieve the same result just with dx expressions?

**Comment by daniel-dx** [comment]
I cann't catch your meaning. can you give a example?
