### ISSUE TITLE
element theme primary color not set for switch

### ISSUE THREAD

**Issue by soundreactor** [ncform/ncform#138]
when i customize an element theme and use it, the primary-color works for the sliders but not for the switch.
is this a bug?
![Screen Shot 2020-04-08 at 17 28 01](https://user-images.githubusercontent.com/4352735/78839559-5bda4600-79be-11ea-8236-605a6a1b88dd.png)

**Comment by daniel-dx** [comment]
You can set the `activeColor` and `inactiveColor` for your needs

**Comment by soundreactor** [comment]
set this where?

**Comment by daniel-dx** [comment]
```
{
  "isOpen": {
    "type": "boolean",
    "ui": {
      "widget": "switch",
      "widgetConfig": {
        "activeColor": "#67C23A",
        "inactiveColor": "#E6A23C"
      }
    }
  }
}
```
