### ISSUE TITLE
怎么才不让ncForm的样式影响到原来的elements的样式

### ISSUE THREAD

**Issue by benyVip** [ncform/ncform#14]
引入了ncForm的新包后，发现原有的样式都被修改了，怎样才能避免样式冲突呢

**Comment by daniel-dx** [comment]
标准组件里有些组件是没加上scope样式限制，后面会出一版全部加上以防影响到项目的样式

**Comment by vencher** [comment]
如果加上scope，对应样式重写会不方便，建议出一版样式文件拆分的版本，方便项目决定是否引用文件。

**Comment by daniel-dx** [comment]
样式用deep模式覆盖就行了

**Comment by melunar** [comment]
建议限定父元素 ncForm 下的样式生效，自己的表单样式不受干扰

**Comment by wukong0506** [comment]
> 标准组件里有些组件是没加上scope样式限制，后面会出一版全部加上以防影响到项目的样式

如何修改ncform的默认样式呢
