### ISSUE TITLE
update the form

### ISSUE THREAD

**Issue by soundreactor** [ncform/ncform#143]
how can i update the form?       
i generate a new properties object and want to update the form.     

i tried:
```
//assigning a new properties object
_vue_element_.formSchema.properties = new_properties;
//updating the vue view
_vue_element_.$forceUpdate();
```

and creating a new VUE . but nothing worked.      
when i create a new VUE all the inputs have no values inside.

**Comment by daniel-dx** [comment]
```
<template>
  <div>
    <ncform :form-schema="formSchema" form-name="your-form-name" v-model="formSchema.value" @submit="submit()"></ncform>
    <el-button @click="submit()">Submit</el-button>
  </div>
</template>
```

If you want to change the form schema dynamically, just change the formSchema object (give it a new one, not just update it's properties)

**Comment by soundreactor** [comment]
how? it won't work. they won't have the default value.

**Comment by soundreactor** [comment]
this worked. thanks. 
is there a way to update the values only? direct from JS. i get new values from the server and i want to update the form values but no reload and re-render the entire form.

**Comment by daniel-dx** [comment]
The same as formSchema, give v-model a new value, not just update it's properties.

**Comment by soundreactor** [comment]
is there a default v-model i can set? or how can i set the v-model for form element? i could not find that in the documentation.

**Comment by daniel-dx** [comment]
You can refer to: https://github.com/ncform/ncform#quick-start

**Comment by soundreactor** [comment]
is there a way to only update one value instead of all? i know i can save the old value object and only change one value, but for my application it won't work like that.

**Comment by daniel-dx** [comment]
Currently there has no api to update partial value. but you can wrap a function for it, may be like this:
```
function updateForm(itemVal, itemPath) { 
  this.$data.formVal = Object.assign({}, _.set(this.$data.formVal, itemPath, itemVal)) 
}
```

**Comment by dhertzb** [comment]
I have this component that receive an array of fields like this:

`[
   {
      "form":"customers",
      "key":"site",
      "standard":true,
      "mandatory":false,
      "active":false,
      "schema":{
         "ui":{
            "label":"Site"
         },
         "type":"string",
         "rules":{
            "url":{
               "value":true,
               "errMsg":"O campo deve ser uma Url."
            },
            "required":{
               "value":false,
               "errMsg":"O campo é obrigatório."
            }
         }
      },
      "configurable":{
         "label":true,
         "widget":true,
         "required":true
      },
      "position":null
   }
]`

![asdasd](https://user-images.githubusercontent.com/45174543/91322649-5f684100-e796-11ea-8ee9-dc47a1a52cd9.png)


If I change the order of the field in the array( if has multiple fields)  the form updates sucefully but when I just change schema.ui.label it remains even if the ncform data instance updates

**1.**
![1](https://user-images.githubusercontent.com/45174543/91323895-c9cdb100-e797-11ea-8843-927f3d1e801b.png)

**2.**
![2](https://user-images.githubusercontent.com/45174543/91323916-d05c2880-e797-11ea-952d-6a3305dd1a9d.png)

**3.**
![3](https://user-images.githubusercontent.com/45174543/91323919-d3571900-e797-11ea-8cc5-6e4279341a04.png)
