### ISSUE TITLE
Undo functionality?

### ISSUE THREAD

**Issue by Lewenhaupt** [ncform/ncform#152]
Hi,

I'm very confused. It appears that pressing ctrl+z for normal text input fields causes an "undo" on that field? I cannot figure out where it originates from and I discovered it when trying to build my own undo/redo functionality. I've removed my own completely and rebuilt/restarted everything and my code is now completely gone. However ctrl+z still triggers the same behavior for the input fields.

**Comment by daniel-dx** [comment]
when you undo/redo, you should reset the form model value, so you must record the form value's history.  

[ncbrick](https://dtc.dx666.fun/) has the undo/redo features for form

**Comment by Lewenhaupt** [comment]
Yeah I know I need to capture the history and all that. The problem is that even when I removed all my undo/redo functionality there is still undo/redo functionality avaialble for the regular input-fields. And I don't know where it's coming from. 
So basically what I'm asking is if you have built anything like this into the input-fields? I'm using the standard element-theme-ui currently. But I've read all the element ui docs and can't find anything related to undo/redo. I can't even find a listener in the browser console that listens to ctrl+z, but still pressing ctrl+z in a input field will result in an undo of that field.

**Comment by Lewenhaupt** [comment]
And also, the link only leads me to a standard nginx default site.

**Comment by daniel-dx** [comment]
> Yeah I know I need to capture the history and all that. The problem is that even when I removed all my undo/redo functionality there is still undo/redo functionality avaialble for the regular input-fields. And I don't know where it's coming from.
> So basically what I'm asking is if you have built anything like this into the input-fields? I'm using the standard element-theme-ui currently. But I've read all the element ui docs and can't find anything related to undo/redo. I can't even find a listener in the browser console that listens to ctrl+z, but still pressing ctrl+z in a input field will result in an undo of that field.

I think this should be the default behavior of the browser. may be you can to go search for how to prevent it

**Comment by Lewenhaupt** [comment]
Ah, apparently at least chrome has an inbuilt one. And simply preventing default on the event would have stopped this... Thanks @daniel-dx
