### ISSUE TITLE
一定要和 element-ui 绑定吗？可以自定义 theme 或不用 theme 吗？

### ISSUE THREAD

**Issue by beetaa** [ncform/ncform#157]
一定要和 element-ui 绑定吗？可以自定义 theme 或不用 theme 吗？谢谢。

**Comment by daniel-dx** [comment]
可以自定义 theme，比如 iview。或者你自己开发的组件库也是可以的。具体可以参考：
- [ncform-theme-vuematerial](https://github.com/daniel-dx/ncform-theme-vuematerial)
- [ncform-theme-iview](https://github.com/F-loat/ncform-theme-iview)

**Comment by beetaa** [comment]
> 可以自定义 theme，比如 iview。或者你自己开发的组件库也是可以的。具体可以参考：
> 
> * [ncform-theme-vuematerial](https://github.com/daniel-dx/ncform-theme-vuematerial)
> * [ncform-theme-iview](https://github.com/F-loat/ncform-theme-iview)

明白，非常感谢。
