### ISSUE TITLE
form-items.vue paths的問題

### ISSUE THREAD

**Issue by shezimanor** [ncform/ncform#162]
問題： schema 結構遇到array類型時，取出的 paths 中 array 裡的 fieldName 會消失。
例如我的資料結構如下：
```
value: {
  a: [
    {
      b: 123,
      c: 456,
      e: [
        {
          f: 789,
          g: 50
        }
      ]
    }
  ]
}
```
假設我修改了g的值時，`onChange` 事件中傳遞的 paths

我預期是 `paths: a[0].e[0].g`，

可是目前得到的卻是 `paths: a[0][0]`， fieldName: e, g 都消失了。

想知道array類型忽略 fieldName 是不是有什麼特別原因，謝謝！

**Comment by F-loat** [comment]
@daniel-dx  我之前就觉得这是个 bug，这样应该就可以修复了 https://github.com/F-loat/ncform/commit/f5f3b2bdcba014195f9a4929bcf9ffa9f4054315

**Comment by daniel-dx** [comment]
@F-loat 好的，我最近发个小版本修复一下
