### ISSUE TITLE
Access validation event inside custom component

### ISSUE THREAD

**Issue by dhertzb** [ncform/ncform#186]
**Why?**
- ncForm provides a way to create logic between components, but sometimes the logic becomes too complex for be handled in the schema. 

**Solution:** 
- create a unique custom component with a complex logic that mostly of the time includes multiple inputs ( with multiple input types  and unique validations) 

**Problem:**
- ncForm dont provide a way to handle the single input validation inside the component, only emits true/false for the whole component.
   1.   Imagine that I have 5 inputs, 2 of them requires validation. I can create a custom validation that verifies if the object emited its is valid and return true/false, but I can't specify which input is invalid.
   2.  To solve the item 1 problem I could create a _**<el-form**_ inside my custom component with it own rules, so if one of two required inputs is invalid the _**<el-form validate()**_ can trigger a specific and visual message for the input. Unfortunately there is no way I can capture the ncForm validate event inside my custom component to trigger the _**<el-form validate**_.

**Comment by daniel-dx** [comment]
You can use el-form rules in custom widgets for validation, because they are internal validation rules

**Comment by dhertzb** [comment]
> You can use el-form rules in custom widgets for validation, because they are internal validation rules

Nice, I didnt know, can you show me an exemple please?
