### ISSUE TITLE
Capturing time fields

### ISSUE THREAD

**Issue by NedDerick** [ncform/ncform#222]
Thanks for a brilliant library! 

I'm trying to generate a from that allows the user to capture a "from-date/time" and a "to-date/time". 

What is the best way to do this with NCForm? 

If I define the fields with a widget of type "datetime" - they get shown a nice date-picker (I don't mind the date part), but I can't find a way to allow them to capture the time.

I tried setting the widget to "datetime-local" - but then VueJs thinks that there is no component called ncform-datetime-local? 

If there is a workaround for this - I would gladly contribute an extra page in the documentation to describe how to do it, so that others can find this easily.

**Comment by daniel-dx** [comment]
Try this: 
```
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "default": "dx: {{+new Date()}}",
      "ui": {
        "widget": "date-picker"
      }
    },
    "email": {
      "type": "string"
    },
    "age": {
      "type": "integer"
    },
    "adult": {
      "type": "boolean"
    }
  }
}
```

You can paste the code to [Playground](https://ncform.github.io/ncform/ncform-show/playground/index.html#tpl=basic)

**Comment by NedDerick** [comment]
Thanks for the help Daniel. If I paste it into playground, I get the date-picker and this time the date is initialized from the dx-expression, but the "time-part" is still missing. 

Is there a way to capture the hours and minutes ?

**Comment by daniel-dx** [comment]
```
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "default": "dx: {{+new Date()}}",
      "ui": {
        "widget": "date-picker",
        "widgetConfig": {
            "type": "datetime"
        }
      }
    },
    "email": {
      "type": "string"
    },
    "age": {
      "type": "integer"
    },
    "adult": {
      "type": "boolean"
    }
  }
}
```

**Comment by daniel-dx** [comment]
If you don't need second, try this:

```
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "default": "dx: {{+new Date()}}",
      "ui": {
        "widget": "date-picker",
        "widgetConfig": {
            "type": "datetime",
            "format": "yyyy-MM-dd HH:mm"
        }
      }
    },
    "email": {
      "type": "string"
    },
    "age": {
      "type": "integer"
    },
    "adult": {
      "type": "boolean"
    }
  }
}
```

**Comment by NedDerick** [comment]
Thanks Daniel. That worked absolutely perfectly. Really cool!!!  

I have one last question, but I'll create another issue for that one - since it;s a little different.
