### ISSUE TITLE
Setting the display language for the datepicker

### ISSUE THREAD

**Issue by NedDerick** [ncform/ncform#223]
I've added this line to my main.js file:  Vue.use(vueNcform, { extComponents: ncformStdComps, lang: 'en' }) in a Vue CLI project.

Even with that in place, the datepicker displays the month names in Chinese (I think). 

Is there a way to force that component to display it's headings in english? 

Many thanks

**Comment by daniel-dx** [comment]
Datapicker is one of the element-ui component, you can refer to [element-ui i18n doc](https://element.eleme.cn/#/en-US/component/i18n)

**Comment by NedDerick** [comment]
Thank you very, very much Daniel.
