### ISSUE TITLE
Small issue with serialization

### ISSUE THREAD

**Issue by NedDerick** [ncform/ncform#240]
Hey Daniel,

I just noticed this and while it might be by design, it tripped me up.... So, thought i would mention it.

When you have a definition like this:
```
{
  "type": "object",
  "properties": {
    "number": {
      "type": "number"
    },
    "string": {
      "type": "string"
    },
    "bool": {
      "type": "boolean"
    }
  }
}
```

If you generate the form and without updating the form in any way - submit the object, the resulting object looks like this:
```
{
"number" : "",
"string: "",
"bool" : false
}
```

The bool defaulted correctly(?) to the false value. The string defaulted to an empty string. The number is the odd one - it evaluated to an empty string.

This means that if you have server side code that tries to parse the Json, it may fail - expecting a numeric value there.

It seems like the quick fix is to simply add "value":0 to the definition and the problem won't appear. 

That's probably a  reasonable thing to do - but it's just sad that it works out of the box for the boolean and not for the number.

Is there some design reason for this that I can't see ?

Kind regards,
Derick

**Comment by daniel-dx** [comment]
For fixing this bug: https://github.com/ncform/ncform/issues/150

**Comment by NedDerick** [comment]
Thanks Daniel. Yeah, that's how I got around it too.  The workaround works perfectly.
