### ISSUE TITLE
是否可以简化v-model='schema.value'?

### ISSUE THREAD

**Issue by CC712** [ncform/ncform#45]
```html
  <ncform :form-schema="formSchema" v-model="formSchema.value" :is-dirty.sync="isFormDirty"></ncform>
```
是否可以用指令简化 `` :form-schema="formSchema" v-model="formSchema.value"``
类似于 这样？
```html
  <ncform v-ncform="formSchema" :is-dirty.sync="isFormDirty"></ncform>
```
```js
    Vue.directive("ncform", (el, binding, vnode) => {
      vnode.componentInstance.formSchema= binding.value;
      vnode.componentInstance.itemValue= binding.value.value;
      vnode.componentInstance.$on("input", payload => {
        binding.value.value = payload;
      });
    });
```

**Comment by daniel-dx** [comment]
你是想这样吧：
```
<div v-ncform="formSchema" :is-dirty.sync="isFormDirty"></div>
```
directive我的理解一般是用于给组件（或原生element）添加行为，比如滚动居顶之类的。如果你是一个组件，还是用组件的声明来吧，这也是vue为什么要区分出component和directive的原因（angular 1.x 就是一切皆directive）

**Comment by daniel-dx** [comment]
`:form-schema="formSchema" v-model="formSchema.value"` 

可能我的例子有点误导，v-model不一定要绑定`formSchema.value` ，可以是data的任一字段，如果按照你的方式，那就真的强制v-model绑定`formSchema.value` 了

**Comment by daniel-dx** [comment]
然后使用`:form-schema="formSchema" v-model="formSchema.value"`这样也比较符合一般人的理解和使用习惯哈。
