### ISSUE TITLE
i18n方案和vue-i18n有冲突

### ISSUE THREAD

**Issue by xuanye** [ncform/ncform#51]
都占用了$t函数，而且没有办法兼容啊

**Comment by daniel-dx** [comment]
在ncform的widget中，使用$t并不会使用vue-i18n的$t方法，而是使用ncform mixins自己的$t方法。

即在ncform widget中，$t是数据来源是widget的i18nData；在ncform widget外部，$t是vue-i18n的方法。经测试，两者是可共存并正常工作的

不过在引入vue-i18n后，会现出$t方法冲突警告，所以ncform会发版不再使用$t方法
