### ISSUE TITLE
显示删除按钮的时候删除按钮位置不对

### ISSUE THREAD

**Issue by q1240641788** [ncform/ncform#65]
删除按钮显示在输入框的下面

**Comment by q1240641788** [comment]
![image](https://user-images.githubusercontent.com/20292432/58413462-65f79c80-80ab-11e9-839b-1202ebe816fe.png)

**Comment by q1240641788** [comment]
还有就是校验触发方式能不能设置，比如离开输入框的时候触发

**Comment by daniel-dx** [comment]
第一个问题：是否样式被影响到？能否提供一些线索?

第二个问题：可以采用扩展自定义组件的方式，然后定义组件触发值更改的机制。目前标准组件的值的变化都是实时的，标准组件不可能满足所有的需求，实际开发中标准组件满足不了的，都可以通过扩展组件来满足

如何扩展请参考文档：[Custom form widget](https://github.com/ncform/ncform/blob/master/EXT-DOC.md#Custom-form-widget)
