### ISSUE TITLE
date-picker能支持非时间戳样式的value吗，如 2019-06-02

### ISSUE THREAD

**Issue by samyhd** [ncform/ncform#68]
目前widget为date-picker类型时，仅能传入时间戳类型，如1512284108066。

这样对于如 “2019-06-02” 或 “2019-06-02 12:20:30” 需要额外再转换一次 

value: Date.parse('2019-4-10 08:12:30') 

能否直接支持这样YYYY—MM-DD之类的传值？（例如传入一个转换格式符或判断不是时间戳就按日期格式来赋值）

**Comment by samyhd** [comment]
目前value需要string，Date.parse的结果是Number，还要再转一次，比较麻烦


                born: {
                  type: 'string',
                  value: Date.parse('2019-4-10 08:12:30')+"",
                  ui: {
                    columns: 4,
                    label: '出生日期',
                    widget: "date-picker",
                    widgetConfig: {
                      "type": "datetime"
                    }
                  }
                },

**Comment by daniel-dx** [comment]
v1.3.2版本 date-picker 标准组件增加了 `valueFormat` 配置项以支持日期格式的输入
