### ISSUE TITLE
是否可以提供组件的事件绑定，如upload想对上传成功做额外处理

### ISSUE THREAD

**Issue by samyhd** [ncform/ncform#70]
有不少组件是需要再进一步绑定事件进行处理的，如upload可以在上传成功后，对返回的文件名、文件大小之类记录

是否可以提供象 :on-success="handleAvatarSuccess" :before-upload="beforeAvatarUpload" 这样来绑定组件的原生事件

这样会更灵活实用，谢谢

**Comment by samyhd** [comment]
当然上面的upload是举例，可能组件封装的value已经能满足上面举例的需求，但是如果能绑定原生事件再作处理是更实用。

**Comment by daniel-dx** [comment]
ncform设计之初就是想靠一份单纯的JSON数据（可保存到服务端）来描述一个表单，所以不想过多地提供绑定事件等机制，但用户可通过自定义widget，在widget里面实现你想做的一切事情，这是跟其它类似开源项目毕竟不一样的地方

然后标准组件并不能满足所有的需求，所以扩展自定义widget在项目开发中是经常会用到的，扩展也是比较简单 : )

**Comment by samyhd** [comment]
我的看法
1）如果表单是保存在服务器上的，那绑定事件是没作用，但是ncform也可以直接用在vue代码中的，也是能大大方便表单编写，这种场景事件就比较在需要了，能提供还是一种增强的，毕竟适用场景是扩大了。
2）您说的扩展组件，但是有些需求只是对目前ncform已封装的组件增加小许功能而已，这样自行去扩展一个有点不太值得，例如upload上ncform上已经有一堆配置了，再自己为了加一个事件重写不太合适。

这只是从我使用上的感受而已，希望能增强做得更好，扩大使用场景，这样我们开箱即用也方便，谢谢。

**Comment by samyhd** [comment]
还有，问些扩展组件的问题
1）能直接从现有ncform已封装的组件如upload上直接继承扩展吗？
2）能提供详细点的扩展组件的文档或Demo吗，现在文档上的那个说得比较简单

![image](https://user-images.githubusercontent.com/10351607/58849827-98625480-86be-11e9-9487-14faf0441650.png)

**Comment by daniel-dx** [comment]
对组件的继承是个很好的想法，后面我再考虑怎么增加这个特性

**Comment by daniel-dx** [comment]
组件的扩展DEMO请参考这个项目[ncform-demo](https://github.com/daniel-dx/ncform-demo)
