### ISSUE TITLE
dx表达式怎样取数组的最后一项内容

### ISSUE THREAD

**Issue by samyhd** [ncform/ncform#72]
FileData字段的value如下

{
    "FileNO":"",
    "FileData":[
        {
            "status":"success",
            "name":"图表_1.jpg",
            "size":61338,
            "percentage":100,
            "uid":1559616801446
        },
        {
            "status":"success",
            "name":"图表_2.jpg",
            "size":85091,
            "percentage":100,
            "uid":1559616810634
        }
    ]
}

另外有个字段如 FileName，它的valueTemplate想关联显示上面数组最后一项的 name

1)如下面的写法能显示第一项的
  valueTemplate: "dx: {{$root.UploadFile.FileData[0].name}}"

2)但我想显示最后一项，如下写法，则没有显示，请问是需要怎样编写
  valueTemplate: "dx: {{$root.UploadFile.FileData[$root.UploadFile.FileData.length - 1].name}}"  

3)如果是写成如下是能取到值的
  valueTemplate: "dx: {{$root.UploadFile.FileData.length}}"  or  valueTemplate: "dx: {{$root.UploadFile.FileData.length}} - 1"  

还有文档说明中的 i变量是什么意思？特定写法？
指定数组中同一项的属性，例子：
disabled: 'dx: {{$root.persons[i].age}} < 18'
disabled: 'dx: {{$root.persons[i + 1].age}} < 18'  

谢谢

**Comment by daniel-dx** [comment]
[i]表示的是数组中的同一项，结合[Playground](https://ncform.github.io/ncform/ncform-show/playground/index.html?lang=cn)中的例子去理解会好点

![image](https://user-images.githubusercontent.com/22042268/58850001-29d1c680-86bf-11e9-893a-5e128fd4f6b4.png)

**Comment by samyhd** [comment]
谢谢，还望帮我看下我的第一个问题。

**Comment by daniel-dx** [comment]
可在 [playground](https://ncform.github.io/ncform/ncform-show/playground/index.html) 下运行
```
{
  "type": "object",
  "properties": {
    "firstname": {
      "type": "array",
      "value": [{"name": "a"}, {"name": "b"}],
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        }
      },
      "ui": {
        "columns": 6
      }
    },
    "lastname": {
      "type": "string",
      "ui": {
        "columns": 6
      }
    },
    "fullname": {
      "type": "string",
      "valueTemplate": "dx: {{$root.firstname}}[{{$root.firstname.length}} - 1]['name']",
      "ui": {
        "columns": 12
      }
    }
  }
}
```
