### ISSUE TITLE
希望增加Switch标准组件

### ISSUE THREAD

**Issue by samyhd** [ncform/ncform#73]
Switch 也比较常用，希望能官方增加上。

这个组件没有那么复杂，自行写扩展也行，但是还要在自己项目中实现这种非特殊业务功能的标准组件，还要加上
`
Vue.use(vueNcform, {
  extComponents: Object.assign(ncformStdComps, { MyCustomComp }),
  extRules: [{ myCustom: MyCustomRule }],
  lang: "" // you can try 'en' or 'zh-cn'
});`

就有点怪怪的感觉。

还是希望官方能加上。谢谢

**Comment by daniel-dx** [comment]
It's a good idea!

如果你能贡献这个组件，那就更好了 :)

**Comment by samyhd** [comment]
我也没写，只是在整体测试时发觉有这个不足。

所以官方提供就最好。

**Comment by daniel-dx** [comment]
@ncform/ncform-theme-elementui 1.5.0 provide this feature
