### ISSUE TITLE
水平布局有没配置表单域标签的宽度（element-ui表单的label-width属性）

### ISSUE THREAD

**Issue by samyhd** [ncform/ncform#74]
在水平布局时，目前看到标签长度是固定为100px的，好似没有开放属性供配置？

对应 element-ui Form Attributes 的 label-width

看到源码中好似有labelWidth，但是在formSchema中加上并没有看到效果

![image](https://user-images.githubusercontent.com/10351607/58934638-a1762300-879d-11e9-89b1-d160a48298d4.png)

期望能加上这个配置，谢谢。

**Comment by daniel-dx** [comment]
这个是在 `object` 布局控制的，如下：

```
{
  "type": "object",
  "properties": {
    "age": {
      "type": "integer",
      "ui": {
        "label": "Age"
      }
    }
  },
  "ui": {
    "widgetConfig": {
      "layout": "h",
      "labelWidth": "120px"
    }
  }
}
```

可粘贴到[playground](https://ncform.github.io/ncform/ncform-show/playground/index.html)看效果

**Comment by samyhd** [comment]
嗯嗯，确实是有，不过当设置了在最外层，并没有覆盖内层的嵌套 列表

![image](https://user-images.githubusercontent.com/10351607/58941692-db9bf080-87ae-11e9-9d71-4d07cd9f3d94.png)


如果能覆盖 觉得更合适一点。

**Comment by daniel-dx** [comment]
现在只能是一层一层设置，因为各个组件的配置是独立的

虽然看上去有点麻烦，但在实际使用中，这种多层嵌套的场景其实不会太多
