### ISSUE TITLE
无法安装 ncform-common

### ISSUE THREAD

**Issue by alenwoo** [ncform/ncform#76]
PS G:\1vue\fast> npm install --save @ncform/ncform ncform/ncform-common
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/ncform/ncform-common.git
npm ERR!
npm ERR! Warning: Permanently added the RSA host key for IP address '13.229.188.59' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

**Comment by daniel-dx** [comment]
`@ncform/ncform-common` 不是 `ncform/ncform-common`，少了个`@`
