### ISSUE TITLE
由没有支持antd for vue的计划啊？

### ISSUE THREAD

**Issue by mseaspring** [ncform/ncform#80]
由没有支持antd for vue的计划啊？如果我项目已经用了antd for vue，我还可以用这个插件，用element-ui做表单处理吗？谢谢

**Comment by daniel-dx** [comment]
支持另外的组件库工作量很大，暂时没计划支持（欢迎贡献）

项目中用了其它的组件库，如antd for vue, iview等，还是可以用element-ui这套的，只是这样子有两个不太好的点，1是项目体积明显变大，2是风格看上去可能会不太一致

如果这两点都觉得不是问题，可以直接引入使用
