### ISSUE TITLE
必填时提醒的"is required" 如何自定义设置?

### ISSUE THREAD

**Issue by passioncsu** [ncform/ncform#81]
必填时提醒的"is required" 非空检查,如何自定义设置,想改成中文

**Comment by daniel-dx** [comment]
![image](https://user-images.githubusercontent.com/22042268/61777513-994a7380-ae2f-11e9-90b5-967cc0dfb664.png)

**Comment by passioncsu** [comment]
非常感谢,我看配置文件太不仔细了,  再问个问题,input组件想用在后面加个单位之类的,elementui也是有这个功能的.  我看了源码
        <template
          slot="append"
          v-if="mergeConfig.compound.appendLabel"
        >{{mergeConfig.compound.appendLabel}}</template>
似乎您也做了这个,但是配置文件里面我还是没找到

**Comment by daniel-dx** [comment]
参考这里：https://ncform.github.io/ncform/ncform-theme-elementui/index.html

**Comment by passioncsu** [comment]
真是非常感谢, 还想问个问题....array的组件,默认都会有一个空行需要填写,  这类似这个
![image](https://user-images.githubusercontent.com/1430270/61843022-c7ca5c00-aecc-11e9-91d4-f18a05993822.png)
有没有配置可以默认为空呢?
![image](https://user-images.githubusercontent.com/1430270/61843044-dfa1e000-aecc-11e9-810a-656bb40b5751.png)

**Comment by passioncsu** [comment]
> 参考这里：https://ncform.github.io/ncform/ncform-theme-elementui/index.html

您好 我楼上这个问个能解答一下吗 非常感谢,不好意思再开新issues
