### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by dhertzb** [ncform/ncform#84]
1) There is a way to change the "Select Please" placeholder?

2) How to attach a event listener that when some input is clicked, only the selected field schema is saved in a const? The thing is: I have a form editor where the user see a preview  of the form, and my idea is that when the user click in one specific input he can edit it and see a preview only for the input, some idea in how to achieve this?

3) How to translate the datepicker?

**Comment by daniel-dx** [comment]
1. You can change the default value by setting the value of "ui.placeholder"

2. There are no any events. but you can track changes by watching the value binding to ncform's v-model

3. the datepicker widget uses element-ui, you can refer to the i18n of element-ui: https://element.eleme.cn/#/en-US/component/i18n

**Comment by dhertzb** [comment]
Thanks, your work here is awesome!

**Comment by daniel-dx** [comment]
oh, the select placeholder in composed input is hardcode now. maybe you can custom your widget by coping the input widget code and modify some

you can refer to [Custom-form-widget](https://github.com/ncform/ncform/blob/master/EXT-DOC.md#Custom-form-widget) to get how

**Comment by daniel-dx** [comment]
I will provide this option in next version as soon as possible.

**Comment by daniel-dx** [comment]
Related issue: #85

**Comment by daniel-dx** [comment]
Yesterday released version 1.4.0.

You can now listen change event to track the value change of form item, not the whole form value
