### ISSUE TITLE
Suggestion to new prop in array-tabs/array-table and a question

### ISSUE THREAD

**Issue by dhertzb** [ncform/ncform#90]
The idea is "propertie to prevent delete only first item but still able to delete the subsequent items in array-tabs/table", an the question is:

Saying that I've a button "showing hidden items" how can I change the fom items state 'hidden' to visible from on click in an external component(button)?

**Comment by daniel-dx** [comment]
> Saying that I've a button "showing hidden items" how can I change the fom items state 'hidden' to visible from on click in an external component(button)?

`computed` data can be used to provide `formSchema` instead of `data`, so that you can dynamically change the form by modifying formSchema externally.

**Comment by daniel-dx** [comment]
> Saying that I've a button "showing hidden items" how can I change the fom items state 'hidden' to visible from on click in an external component(button)?

You can dynamically modify the form by giving the form-schema a new value, as shown below

```
  <div id="demo">
    <ncform :form-schema="formSchema" form-name="your-form-name" v-model="formSchema.value"></ncform>
    <el-button @click="showName()">Show Name</el-button>
  </div>


    new Vue({
      el: '#demo',
      data: {
        formSchema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              ui: {
                hidden: true
              }
            }
          }
        }
      },
      methods: {
        showName() {
          let newFormSchema = _.cloneDeep(this.$data.formSchema);
          newFormSchema.properties.name.ui.hidden = false;
          this.$data.formSchema = newFormSchema;
        }
      }
    });
```

**Comment by dhertzb** [comment]
Oh, it work like a charm, tnks a lot! The propertie that I mentioned is important at least in my aplication as in example:

I've a client registration where the phone number is required, but the user can register more optional numbers clicking in "+" in the array tab, so only the first item must not be delectable

Thank you again your work is phenomenal

**Comment by daniel-dx** [comment]
hi, you can add required rule to your phone number of array type
