### ISSUE TITLE
Mask and custom validation

### ISSUE THREAD

**Issue by dhertzb** [ncform/ncform#91]
1º There is a way to implement a mask something like cleave.js?

User write 07865253982 and it show 078.652.539.82, the pattern validation only check for this mask and not aply it, right?

2º My validation rule isn't working as I'm typing in the input it appears this error : 不存在验证规则myCustom,  if you show me a example of implementation I would apreciate

/////// cepValidation.js
```
import ncformCommon from '@ncform/ncform-common';

class MyCustomRule extends ncformCommon.ValidationRule {

  constructor(props) {
    super(props);
    this.name = 'myCustom'; // your rule name
    this.defaultErrMsg = 'Digite um cep válido.'; // you rule default error message tips
  }

  validateLogic(val, ruleVal) {
    
    return val.length > 3;
  }

}

export default MyCustomRule;`
```

//////Component
```
import MyCustomRule from '../../../common-components/form-validation/cepValidation'

Vue.use(vueNcform, { extComponents: ncformStdComps}, {extRules: [{myCustom: MyCustomRule}]});

"rules":{
	myCustom: {
		value: true
        }
}
```

**Comment by daniel-dx** [comment]
### Point 2

- Wrong
```
Vue.use(vueNcform, { extComponents: ncformStdComps}, {extRules: [{myCustom: MyCustomRule}]});
```
- Right
```
Vue.use(vueNcform, {
  extComponents: ncformStdComps,
  extRules: [{ myCustom: MyCustomRule }],
});
```

**Comment by dhertzb** [comment]
Ok, one more question, I've a location array-tab with country - state - city consuming geoname api, so far so good. Those are requeried fields.

So as example an user could choose, Brasil -> Rio de Janeiro -> Rio de Janeiro.

But I've another input, zip code, that is opcional. What I need is when an user type the postal code and it pass validation, it will get an json from an Api an update the country - state - city acording to the json.
    {
      "zipcode": "01001-000",
      "street": "Praça da Sé",
      "district": "Sé",
      "city": "São Paulo"
    }

Follow the example after user type postal code the country still would be Brazil, state would change to São Paul and city to São Paulo.

To achieve this I an aware that I need a custom widget, but how can I change the other inputs after I get the json with axios?

**Comment by daniel-dx** [comment]
Hi, you can refer to the example at [playground](https://ncform.github.io/ncform/ncform-show/playground/index.html)

![image](https://user-images.githubusercontent.com/22042268/64483531-e2b31e80-d235-11e9-9f0f-e02b47e6023b.png)

You can change `enumSource` to `enumSourceRemote`，and the API returns the response like

```
[
  {
  "zipcode": "01001-000",
  "street": "Praça da Sé",
  "district": "Sé",
  "city": "São Paulo"
  }
]
```

and other fields can use the value like

```
"valueTemplate": "dx: {{$temp.selectedItem.street}} || \"\""
```

**Comment by dhertzb** [comment]
The city, state, api is a different api from the postal code, and it has to be triggered just if the postal code is valid.
![dddd](https://user-images.githubusercontent.com/45174543/64494380-70a4fe80-d262-11e9-91fd-28ac535c9cd5.jpg)

**Comment by daniel-dx** [comment]
Refer to the example: https://codepen.io/danielxiaowxx/pen/ExYQBvG

If you give value "1000" to the postCode, you will find the dataSource of province changed to "Shanghai"

The problem of the example is that whenever you fill in one number, a request is made. You can consider implementing your own INPUT and then triggering the change event when blur.

**Comment by dhertzb** [comment]
Thank you!
