### ISSUE TITLE
array-tabs 里每个 tab-pane 内容相同

### ISSUE THREAD

**Issue by LiuduZero** [ncform/ncform#92]
根据官网里设置的  schema 渲染出来的 tabs 中每个 tabpane 里都是一样的表单，而实际情况是每个 tabpane 都是由差异的，这种该如何实现呢

**Comment by daniel-dx** [comment]
这里的tab只是数组结构数据的一种表现，而数组在定义的时候，每一项的数据结构都是一致的，不支持不同Tab不同的数据结构哦

**Comment by LiuduZero** [comment]
> 这里的tab只是数组结构数据的一种展示形式（其它数组展示形式如table），而数组在定义的时候，每一项的数据结构都是一致的，不支持不同Tab不同的数据结构哦

了解了解
