### ISSUE TITLE
如果我现在form的json 想从后端生成，map怎么在传输中保持有序呢。

### ISSUE THREAD

**Issue by fitan** [ncform/ncform#94]

**Comment by daniel-dx** [comment]
在JS的对象中，key的顺序与key的加入顺序有关，所以为了保持表单生成字段的顺序，在给到ncform时，schema的字段的顺序要正确，当前schema没有提供类似`sort`的字段，所以需要使用者自行排序。举个例子：

你的schema的如下：

```
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "age": {
      "type": "integer"
    },
    "adult": {
      "type": "boolean"
    }
  }
}
```

现在想按这样排序：name，adult，age，email。你可以这样做：

```
// 以下只是为了描述清楚，没做代码的优化
const schema = {
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "age": {
      "type": "integer"
    },
    "adult": {
      "type": "boolean"
    }
  }
}

const fieldsOrder = ['name', 'adult', 'age', 'email']
let newSchema = {
  type: 'object',
  properties: {}
}
fieldsOrder.forEach(key => {
  newSchema.properties[key] = schema.properties[key];
})
console.log(JSON.stringify(newSchema, null, 2))

```

当然，还是建议在后端生成form schema的时候就是按想要的顺序去增加key

**Comment by fitan** [comment]
懂了

> 在JS的对象中，key的顺序与key的加入顺序有关，所以为了保持表单生成字段的顺序，在给到ncform时，schema的字段的顺序要正确，当前schema没有提供类似`sort`的字段，所以需要使用者自行排序。举个例子：
> 
> 你的schema的如下：
> 
> ```
> {
>   "type": "object",
>   "properties": {
>     "name": {
>       "type": "string"
>     },
>     "email": {
>       "type": "string"
>     },
>     "age": {
>       "type": "integer"
>     },
>     "adult": {
>       "type": "boolean"
>     }
>   }
> }
> ```
> 
> 现在想按这样排序：name，adult，age，email。你可以这样做：
> 
> ```
> // 以下只是为了描述清楚，没做代码的优化
> const schema = {
>   "type": "object",
>   "properties": {
>     "name": {
>       "type": "string"
>     },
>     "email": {
>       "type": "string"
>     },
>     "age": {
>       "type": "integer"
>     },
>     "adult": {
>       "type": "boolean"
>     }
>   }
> }
> 
> const fieldsOrder = ['name', 'adult', 'age', 'email']
> let newSchema = {
>   type: 'object',
>   properties: {}
> }
> fieldsOrder.forEach(key => {
>   newSchema.properties[key] = schema.properties[key];
> })
> console.log(JSON.stringify(newSchema, null, 2))
> ```
> 
> 当然，还是建议在后端生成form schema的时候就是按想要的顺序去增加key

懂了 感谢
