### ISSUE TITLE
请问事件是如何传递的呢？

### ISSUE THREAD

**Issue by mimimile** [ncform/ncform#95]

**Comment by daniel-dx** [comment]
ncform只有的`submit`和`change`事件，表单项之间的交互都是通过监听form value值的变化来实现的

**Comment by mimimile** [comment]
@daniel-dx 如果是多个表单 怎样避免冲突的呢

**Comment by daniel-dx** [comment]
多个表单通过 formName 进行区分，所以你可以看到一些 API 是通过提供 formName 来调用的，比如：

```
this.$ncformValidate('demoForm')
```
